import type { EnvMap, SchemaType } from './types.js';

const PORT_KEY_PATTERN = /(^|_)(PORT|PORTS)$/u;

export function generateSchema(env: EnvMap): string {
  const lines = [
    '# Generated by dotlint init',
    '# Review each entry: set required or optional, adjust types, and add desc=',
    '# Full format: VAR_NAME required|optional type=string|number|boolean|url|port default=VALUE desc=Description',
    ''
  ];

  for (const [key, value] of env) {
    const required = value === '' ? 'optional' : 'required';
    const type = inferType(key, value);
    lines.push(`${key} ${required} type=${type}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function inferType(key: string, value: string): SchemaType {
  if (value === '') {
    return 'string';
  }

  const normalized = value.toLowerCase();
  if (['true', 'false', '1', '0', 'yes', 'no'].includes(normalized)) {
    return 'boolean';
  }

  if (value.startsWith('http://') || value.startsWith('https://')) {
    return 'url';
  }

  const numericValue = Number(value);
  if (
    PORT_KEY_PATTERN.test(key) &&
    Number.isInteger(numericValue) &&
    numericValue >= 1 &&
    numericValue <= 65535
  ) {
    return 'port';
  }

  if (Number.isFinite(numericValue)) {
    return 'number';
  }

  return 'string';
}
