'use strict';

/**
 * Generates a starter .env.schema from an existing .env file.
 *
 * Each key in the .env becomes a schema entry with:
 * - required=true (conservative default - user can relax to optional)
 * - type inferred from the value
 * - no description (user fills in)
 *
 * The output is a valid .env.schema file ready to commit.
 *
 * @param {Map<string, string>} env - parsed .env content
 * @returns {string} .env.schema file content
 */
function generateSchema(env) {
  const lines = [
    '# Generated by envlint init',
    '# Review each entry: set required/optional, adjust types, add desc=',
    '# Full format: VAR_NAME required|optional type=string|number|boolean|url|port default=VALUE desc=Description',
    '',
  ];

  for (const [key, value] of env) {
    const type = inferType(value);
    const required = value !== '' ? 'required' : 'optional';
    lines.push(`${key} ${required} type=${type}`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Infers a schema type from a concrete value.
 *
 * The inference is heuristic and errs toward specificity:
 * - Numbers before strings (many secrets look like numbers but should be strings)
 * - Booleans are recognized by canonical values
 * - URLs are recognized by protocol prefix
 * - Port numbers are recognized as integers in 1-65535 range
 *
 * @param {string} value
 * @returns {'string'|'number'|'boolean'|'url'|'port'}
 */
function inferType(value) {
  if (value === '') {
    return 'string';
  }

  const lower = value.toLowerCase();

  if (['true', 'false', '1', '0', 'yes', 'no'].includes(lower)) {
    return 'boolean';
  }

  if (value.startsWith('http://') || value.startsWith('https://')) {
    return 'url';
  }

  const asNumber = Number(value);
  if (Number.isInteger(asNumber) && asNumber >= 1 && asNumber <= 65535) {
    return 'port';
  }

  if (Number.isFinite(asNumber) && value.trim() !== '') {
    return 'number';
  }

  return 'string';
}

module.exports = { generateSchema };
